### ISSUE TITLE
Publishing docs

### ISSUE THREAD

**Issue by GuettnerBianca** [sisyga/biolgca#33]
I'd suggest publishing them on GitHub pages since they have an integration with GitHub such that we can have it generate the documentation automatically every time we push to a certain branch (and, optionally, after successfully running tests on that). More on how to start this can be found [here](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site), but I can't do it yet because our repo needs to be public in order to set up GitHub Pages with a free account.

I can deal with the fine tuning when the site exists :)

**Comment by sisyga** [comment]
I published the repository and set up *Read the Docs* which now automatically compiles the documentation after each push to the master branch
